version: 2.1

orbs:
  python: circleci/python@1.3.2

jobs:
  lint:
    executor: python/default
    steps:
      - checkout
      - run:
          command: pip install black
          name: Install black
      - run:
          command: black --check .
          name: Run black
  test:
    executor: python/default
    steps:
      - checkout
      - python/dist
      - run:
          command: pip install pytest
          name: Install pytest
      - run:
          command: python tests/utils/init_db.py
          name: Initialize test database
      - run:
          command: python -m pytest
          name: Run tests

workflows:
  main:
    jobs:
      - lint
      - test
      - hold:
          type: approval
          requires:
            - lint
            - test
